version: "2.1"

services:
  redis-proxy:
    build: .
    container_name: redis-proxy
    ports:
      - 36379:6379
    environment:
      - LISTEN=:6379
      - SENTINEL=:26379
      - MASTER=mymaster
      - PASSWORD=
